const resList = [
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "1",
      name: "Meghana Foods",
      totalRatingString: "500+ ratings",
      cuisines: ["Burgers", "Biryani", "American", "Snacks", "Fast Food"],
      costForTwo: 40000,
      cloudinaryImageId: "https://th.bing.com/th/id/OIP.yzHHolIfqny7Gn7mh69QlAAAAA?pid=ImgDet&w=179&h=119&c=7&dpr=1.3",
      costForTwo: "$400 for two",
      deliveryTime: 36,
      minDeliveryTime: 36,
      maxDeliveryTime: 36,
      avgRating: "3.8",
    },
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "2",
      name: "New Green Bawarchi",
      totalRatingString: "500+ ratings",
      cuisine: ["Biryani", "Chinese", "Haleem"],
      costForTwo: 179,
      imageId: "https://th.bing.com/th/id/OIP.00Wmw6Em3wos1ZszvaneeQHaEK?w=299&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
      costForTwoString: "$40 off above $179",
      deliveryTime: 35,
      minDeliveryTime: 30,
      maxDeliveryTime: 35,
      avgRating: "3.8",
    },
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "3",
      name: "Daily Kitchen",
      totalRatingString: "500+ ratings",
      cuisine: ["Home Food", "Indian", "North Indian"],
      costForTwo: 12000,
      imageId: "https://th.bing.com/th/id/OIP.Qb5vqlxQyT9aOlcVq248ogHaE8?w=285&h=190&c=7&r=0&o=5&dpr=1.3&pid=1.7",
      costForTwoString: "60% off up to $120",
      deliveryTime: 25,
      minDeliveryTime: 15,
      maxDeliveryTime: 25,
      avgRating: "4.0",
    },
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "4",
      name: "Pizza Hut",
      totalRatingString: "500+ ratings",
      cuisine: ["Pizzas"],
      costForTwo: 18900,
      imageId: "https://th.bing.com/th/id/OIP.Z_xx18BD1vzcU1r6S9sR9wHaEd?pid=ImgDet&w=179&h=107&c=7&dpr=1.3",
      costForTwoString: "$189",
      deliveryTime: 36,
      minDeliveryTime: 36,
      maxDeliveryTime: 36,
      avgRating: "3.5",
    },
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "5",
      name: "Haldiram's Restaurant",
      totalRatingString: "500+ ratings",
      cuisine: ["North Indian", "South Indian", "Biryani", "Snacks", "Fast Food"],
      costForTwo: 40000,
      imageId: "https://assets.telegraphindia.com/telegraph/2022/Dec/1671711298_2-25.jpg",
      costForTwoString: "$400 for two",
      deliveryTime: 30,
      minDeliveryTime: 25,
      maxDeliveryTime: 25,
      avgRating: "3.4",
    },
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "6",
      name: "Family Dhaba",
      totalRatingString: "500+ ratings",
      cuisine: ["North Indian"],
      costForTwo: 40000,
      imageId: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/lm0zexw0ulqsisuvhjaj",
      costForTwoString: "$400 for one",
      deliveryTime: 30,
      minDeliveryTime: 25,
      maxDeliveryTime: 35,
      avgRating: "4.5",
    },
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "7",
      name: "AR Bakers",
      totalRatingString: "500+ ratings",
      cuisine: ["Cakes", "Biscuits", "Cupcakes", "Snacks"],
      costForTwo: 40000,
      imageId: "https://th.bing.com/th/id/OIP.xxv7FLFud_1HxHE8DEjgMAAAAA?w=202&h=303&c=7&r=0&o=5&dpr=1.3&pid=1.7",
      costForTwoString: "$400",
      deliveryTime: 30,
      minDeliveryTime: 25,
      maxDeliveryTime: 25,
      avgRating: "4.5",
    },
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "8",
      name: "Bawarchi Restaurant",
      totalRatingString: "500+ ratings",
      cuisine: ["North Indian", "South Indian", "Biryani", "Snacks", "Fast Food"],
      costForTwo: 50000,
      imageId: "https://th.bing.com/th/id/OIP.Cwm48VkbLD5N9spqoK4egQHaFj?pid=ImgDet&w=179&h=134&c=7&dpr=1.3",
      costForTwoString: "$500",
      deliveryTime: 30,
      minDeliveryTime: 25,
      maxDeliveryTime: 25,
      avgRating: "3.4",
    },
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "9",
      name: "Haldiram's Restaurant",
      totalRatingString: "500+ ratings",
      cuisine: ["North Indian", "South Indian", "Biryani", "Snacks", "Fast Food"],
      costForTwo: 40000,
      imageId: "https://assets.telegraphindia.com/telegraph/2022/Dec/1671711298_2-25.jpg",
      costForTwoString: "$400 for two",
      deliveryTime: 30,
      minDeliveryTime: 25,
      maxDeliveryTime: 25,
      avgRating: "4.2",
    },
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "10",
      name: "Haldiram's Restaurant",
      totalRatingString: "500+ ratings",
      cuisine: ["North Indian", "South Indian", "Biryani", "Snacks", "Fast Food"],
      costForTwo: 40000,
      imageId: "https://assets.telegraphindia.com/telegraph/2022/Dec/1671711298_2-25.jpg",
      costForTwoString: "$400 for two",
      deliveryTime: 30,
      minDeliveryTime: 25,
      maxDeliveryTime: 25,
      avgRating: "3.4",
    },
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "11",
      name: "Haldiram's Restaurant",
      totalRatingString: "500+ ratings",
      cuisine: ["North Indian", "South Indian", "Biryani", "Snacks", "Fast Food"],
      costForTwo: 40000,
      imageId: "https://assets.telegraphindia.com/telegraph/2022/Dec/1671711298_2-25.jpg",
      costForTwoString: "$400 for two",
      deliveryTime: 30,
      minDeliveryTime: 25,
      maxDeliveryTime: 25,
      avgRating: "4.8",
    },
  },
];

export default resList;
